# Generated by Django 4.1.1 on 2022-09-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_comments_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='course.comments'),
            preserve_default=False,
        ),
    ]
