# Generated by Django 4.1.1 on 2022-09-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courses_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_course', to='course.comments'),
        ),
    ]
